-- AlterTable
-- Marks hooks minted by the live AI auto-generator so they fire to learners
-- via HookOverlay but stay hidden from the presenter's composer/history.
ALTER TABLE "live_hooks" ADD COLUMN IF NOT EXISTS "autoGenerated" BOOLEAN NOT NULL DEFAULT false;
